Swarinfo 546 user guide 5 interloc
SwarmUS/SwarmUS-doc pull request #20
Opened 2021-11-17 19:34 UTC by stlaperriere

2021-11-18 14:12 UTC, cquesnel requested changes

2021-11-18 14:12 UTC, cquesnel commented on docs/sections/user-guide/basic-examples/basic-interloc.md
> +Like said earlier, Buzz has a neighbor management feature, which allows to access the position of the other agents, among other things.
I think "As said earlier" would be a little nicer

2021-11-18 14:12 UTC, cquesnel commented on docs/sections/user-guide/basic-examples/basic-interloc.md
> +  stig.put("leader", 1);
I think this is a hybrid code that was done between two demos. Here we put something in the stigmergy to never use it afterwards...

2021-11-18 14:12 UTC, cquesnel commented on docs/sections/user-guide/basic-examples/basic-interloc.md
> +            var goal = math.vec2.newp(neighbor.distance - 0.5, neighbor.azimuth);
I know you don't want to document all the Buzz features, but I would at least introduce what is in the neighbors structure, because here `azimuth` comes out of nowhere without any information as to what it represents.

I would also add a line explaining and linking to documentation of the math.vec2 library we are using here. (Ask @xgroleau  where to find it)

2021-11-18 14:12 UTC, cquesnel commented on docs/sections/user-guide/basic-examples/basic-interloc.md
> +        if(is_table(neighbor)){
A few coments in the code wouldn't hurt, for someone who has never read buzz code, some concepts could be pretty obscure

2021-11-18 14:52 UTC, stlaperriere commented on docs/sections/user-guide/basic-examples/basic-interloc.md
> +        if(is_table(neighbor)){
Honestly, everything is well documented here : https://github.com/buzz-lang/Buzz/blob/master/doc/api.md#neighbors

2021-11-18 15:09 UTC, stlaperriere commented on docs/sections/user-guide/basic-examples/basic-interloc.md
> +            var goal = math.vec2.newp(neighbor.distance - 0.5, neighbor.azimuth);
found it

2021-11-18 16:36 UTC, stlaperriere commented on docs/sections/user-guide/basic-examples/basic-interloc.md
> +One of the key features of the SwarmUS platform is the ability for a given Hiveboard to determine the position of other Hiveboards with respect to its own position. This page shows how to use this *i
I changed the links

2021-11-19 13:51 UTC, cquesnel approved these changes

2021-11-19 14:08 UTC, merged