Swarinfo 498/hivear doc reference
SwarmUS/SwarmUS-doc pull request #22
Opened 2021-11-21 16:39 UTC by t-constantin

2021-11-21 19:13 UTC, stlaperriere commented
I've got 3 warnings in the console when I do `mkdocs serve`. Maybe double check the hyperlinks :

```
WARNING  -  Documentation file 'sections/reference/HiveAR/hivear-preface.md' contains a link to
            'sections/reference/HiveAR/..\Networking\configure-wifi.md' which is not found in the documentation
            files.
WARNING  -  Documentation file 'sections/reference/Networking/configure-wifi.md' contains a link to
            'sections/reference/Networking/..\HiveAR\hivear-preface.md' which is not found in the documentation
            files.
WARNING  -  Documentation file 'sections/reference/Networking/configure-wifi.md' contains a link to
            'sections/reference/Networking/..\HiveAR\hivear-preface.md' which is not found in the documentation
            files.
```

2021-11-21 20:10 UTC, stlaperriere requested changes
GJ, it's quite thorough.

2021-11-21 21:29 UTC, t-constantin commented on docs/sections/reference/HiveAR/hivear-setup.md
> +In order to use HiveAR, first download the application from the [GitHub](https://github.com/SwarmUS/HiveAR) page and install accordingly to the instructions in the same page.
Yes my next goal is to change the Github page documentation where I thought it would be useful to have the installation process. (that was the next task I was about to start) ;)

2021-11-21 21:29 UTC, t-constantin commented on docs/sections/reference/HiveAR/hivear-setup.md
> +TODO
true, i'll add that

2021-11-21 21:55 UTC, t-constantin commented on docs/sections/reference/HiveAR/hivear-preface.md
> +The codebase for HiveAR is hosted on [GitHub](https://github.com/SwarmUS/HiveAR).
same answer

2021-11-24 13:16 UTC, stlaperriere approved these changes

2021-11-24 13:40 UTC, merged