Feat/swarinfo 470 hivemind buzz reference
SwarmUS/SwarmUS-doc pull request #3
Opened 2021-09-02 19:42 UTC by xgroleau

2021-09-02 21:58 UTC, stlaperriere requested changes

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/bbzvm/index.md
> +In addition to the functions added to the global namespace, a math library was added to make some calculation possible. You can get the documentation of the available symbols [here](https://swarmus.g
proposition : "[...] math namespace. Thus, calling the `max` function must be done by prefixing the namespace (e.g. `math.max(0, 1); # returns 1`)."

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-api.md
> +![Message hierarchy](img/message-hierarchy.png)
Add a white background to the image, it is hard to see in mkdocs in dark mode

And just to be sure: `Interlock` or `interloc`?

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-api.md
> +          Used to call a function to a host or buzz script. The function name needs to match the one that was registered, the number of arguments and their types needs to match.
Maybe add a link to the `Defining Callbacks` page of HiveMindBridge since there is some info about this

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-host.md
> +For example, the HiveMind could request the robot to move to an x,y position, relative to its current position, thus the "moveBy" function would be called on the host.
refer to a HiveMindBridge page since this is closely related.

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-host.md
> +To be a host you need to implement all the functionalities in the Request and Response messages, since this can be time consuming, a C++ implementation is already provided [here](https://github.com/S
Refer to the documentation pages of the bridge instead of the source code, since the bridge is a part of the project

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-preface.md
> +- Provides an API for the host robot. The API allows:
Link to the API page

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-api.md
> +# HiveMind API
General comment : this page is rather a wall of text. Could you use hierarchical titles instead of bullet points?

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-preface.md
> +    - Call a buzz function in the swarm
I feel like these bullet points could each have a link to the paragraph that explains the feature in the API page.

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-swarm.md
> +For example: The buzz script calls `getStatus()` on it's local host, the message is rooted by the HiveMind and sent to the host. The host could then call `returnGetStatus(status)` to "return" the val
you mean routed?

2021-09-02 21:58 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-swarm.md
> +Here by "user" we means someone either someone that wants to implement swarm behavior, or someone that implement the code for a robot to be a host for the HiveMind. The swarm behavior will mostly wri
This whole paragraph is confusing to me. What are we trying to say? And it feels as this should not be the  conclusion of a section, but rather something in the preamble. What do you think?

2021-09-05 19:16 UTC, xgroleau commented on docs/sections/reference/HiveMind/hivemind-host.md
> +For example, the HiveMind could request the robot to move to an x,y position, relative to its current position, thus the "moveBy" function would be called on the host.
Already reference at the end of the page, though it's a reference to the github repo since HiveMindBridge doesn't have an index page

2021-09-05 19:17 UTC, xgroleau commented on docs/sections/reference/HiveMind/hivemind-host.md
> +For example, the HiveMind could request the robot to move to an x,y position, relative to its current position, thus the "moveBy" function would be called on the host.
Which page though? The HiveMindBridge doesn't have an index/preface page like stated in the comment.

2021-09-05 19:18 UTC, xgroleau commented on docs/sections/reference/HiveMind/hivemind-host.md
> +To be a host you need to implement all the functionalities in the Request and Response messages, since this can be time consuming, a C++ implementation is already provided [here](https://github.com/S
Which page though? The HiveMindBridge doesn't have an index/preface page like stated in the comment.

2021-09-05 19:26 UTC, xgroleau commented on docs/sections/reference/HiveMind/hivemind-api.md
> +# HiveMind API
I tried but honestly it was worse since you can't really see the hierarchy easily

![image](https://user-images.githubusercontent.com/31734358/132139030-a9f35b51-2665-4f52-a7e3-ca33f55eabb4.png)

2021-09-05 19:33 UTC, xgroleau commented on docs/sections/reference/HiveMind/hivemind-swarm.md
> +Here by "user" we means someone either someone that wants to implement swarm behavior, or someone that implement the code for a robot to be a host for the HiveMind. The swarm behavior will mostly wri
I just removed it, made more sense in the old doc since it was at the beginning

2021-09-09 11:43 UTC, stlaperriere approved these changes

2021-09-09 11:43 UTC, stlaperriere commented on docs/sections/reference/HiveMind/hivemind-host.md
> +To be a host you need to implement all the functionalities in the Request and Response messages, since this can be time consuming, a C++ implementation is already provided [here](https://github.com/S
You could refer to the Getting started page from User Guides. It contains many links to the reference pages.

2021-09-11 00:57 UTC, merged